name: PR Style Bot

on:
  issue_comment:
    types: [created]

jobs:
  run-style-bot:
    if: >
      contains(github.event.comment.body, '@bot /style') &&
      github.event.issue.pull_request != null
    runs-on: ubuntu-latest

    steps:
      - name: Extract PR details
        id: pr_info
        uses: actions/github-script@v6
        with:
            script: |
                const prNumber = context.payload.issue.number;
                const { data: pr } = await github.rest.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: prNumber
                });
                return { prNumber: prNumber, headRef: pr.head.ref, cloneUrl: pr.head.repo.clone_url };

      - name: Check out PR branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ steps.pr_info.outputs.headRef }}
      
      - name: Set up Python
        uses: actions/setup-python@v4

      # If your `style` and `quality` commands require dependencies or setup,
      # install them here. For example:
      - name: Install dependencies
        run: |
          pip install .

      - name: Run make style and make quality
        run: |
          make style && make quality

      - name: Commit and push changes
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # If there are changes after running style/quality, commit them
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Apply style fixes"
            # Push back to the PR branch
            git push origin HEAD:${{ steps.pr_info.outputs.headRef }}
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
