name: Run Tests After Style Bot

on:
  workflow_run:
    workflows: ["PR Style Bot"]  # Adjust to match your style bot workflow name
    types:
      - completed

permissions:
  checks: write
  contents: write

jobs:
  run_tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Create check run
        id: create_check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: check } = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'PR Tests After Style Bot',
              head_sha: context.sha,
              status: 'in_progress',
            });
            return { check_id: check.id };
      
      - name: Run tests using reusable workflow
        uses: ./.github/workflows/run-workflow.yml@main
        with:
          python_version: '3.9'
      
      - name: Complete check run
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const checkId = ${{ steps.create_check.outputs.check_id }};
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: checkId,
              conclusion: 'success',
              output: {
                title: 'Tests Completed',
                summary: 'All tests passed.',
              },
            });
